// <auto-generated />
using System;
using DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(StudentRegisterContext))]
    [Migration("20251209123030_seeding")]
    partial class seeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CourseStudent", b =>
                {
                    b.Property<string>("CoursesId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StudentsId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CoursesId", "StudentsId");

                    b.HasIndex("StudentsId");

                    b.ToTable("CourseStudent");

                    b.HasData(
                        new
                        {
                            CoursesId = "55c59bce-fdf7-4e46-8da5-04bd51fb7ca3",
                            StudentsId = "b8f9f496-1f7d-4a4a-a4b3-01c4b2d44f78"
                        },
                        new
                        {
                            CoursesId = "55c59bce-fdf7-4e46-8da5-04bd51fb7ca3",
                            StudentsId = "c7a129fc-1e41-4bb3-a1b7-20560b4a0390"
                        },
                        new
                        {
                            CoursesId = "55c59bce-fdf7-4e46-8da5-04bd51fb7ca3",
                            StudentsId = "ce7ada32-7649-4f0a-b64f-dfe3b98b6f09"
                        },
                        new
                        {
                            CoursesId = "320ca047-6db9-46ce-9389-f208a8e6b2ed",
                            StudentsId = "b8f9f496-1f7d-4a4a-a4b3-01c4b2d44f78"
                        },
                        new
                        {
                            CoursesId = "320ca047-6db9-46ce-9389-f208a8e6b2ed",
                            StudentsId = "c7a129fc-1e41-4bb3-a1b7-20560b4a0390"
                        },
                        new
                        {
                            CoursesId = "b8a94b7d-cc67-46ec-84df-9bf0d060a71c",
                            StudentsId = "b8f9f496-1f7d-4a4a-a4b3-01c4b2d44f78"
                        },
                        new
                        {
                            CoursesId = "b8a94b7d-cc67-46ec-84df-9bf0d060a71c",
                            StudentsId = "da4a48c4-b2f4-4005-a2ad-bf10b72c4f56"
                        },
                        new
                        {
                            CoursesId = "b8a94b7d-cc67-46ec-84df-9bf0d060a71c",
                            StudentsId = "ce7ada32-7649-4f0a-b64f-dfe3b98b6f09"
                        },
                        new
                        {
                            CoursesId = "6ada9e49-4939-404d-8163-fe8b466ce5cf",
                            StudentsId = "da4a48c4-b2f4-4005-a2ad-bf10b72c4f56"
                        },
                        new
                        {
                            CoursesId = "6ada9e49-4939-404d-8163-fe8b466ce5cf",
                            StudentsId = "6495a526-21fe-4994-8db3-d56c2500fb06"
                        });
                });

            modelBuilder.Entity("DAL.Models.Course", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = "55c59bce-fdf7-4e46-8da5-04bd51fb7ca3",
                            Name = "React"
                        },
                        new
                        {
                            Id = "320ca047-6db9-46ce-9389-f208a8e6b2ed",
                            Name = "CSS"
                        },
                        new
                        {
                            Id = "b8a94b7d-cc67-46ec-84df-9bf0d060a71c",
                            Name = "HTML"
                        },
                        new
                        {
                            Id = "6ada9e49-4939-404d-8163-fe8b466ce5cf",
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = "36370279-e7d1-4345-bcfe-785dba0c0d96",
                            Name = "Angular"
                        });
                });

            modelBuilder.Entity("DAL.Models.Student", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = "b8f9f496-1f7d-4a4a-a4b3-01c4b2d44f78",
                            Address = "Cairo",
                            DateOfBirth = new DateTime(2000, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ahmed.ali@example.com",
                            Name = "Ahmed Ali",
                            Phono = "01012345678"
                        },
                        new
                        {
                            Id = "c7a129fc-1e41-4bb3-a1b7-20560b4a0390",
                            Address = "Giza",
                            DateOfBirth = new DateTime(1999, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mariam.hassan@example.com",
                            Name = "Mariam Hassan",
                            Phono = "01198765432"
                        },
                        new
                        {
                            Id = "da4a48c4-b2f4-4005-a2ad-bf10b72c4f56",
                            Address = "Alexandria",
                            DateOfBirth = new DateTime(2001, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "omar.mohamed@example.com",
                            Name = "Omar Mohamed",
                            Phono = "01234567890"
                        },
                        new
                        {
                            Id = "ce7ada32-7649-4f0a-b64f-dfe3b98b6f09",
                            Address = "Cairo",
                            DateOfBirth = new DateTime(2001, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Manar.mohamed@example.com",
                            Name = "Manar Mohamed",
                            Phono = "01234567890"
                        },
                        new
                        {
                            Id = "6495a526-21fe-4994-8db3-d56c2500fb06",
                            Address = "Alexandria",
                            DateOfBirth = new DateTime(2001, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Ziad.mohamed@example.com",
                            Name = "Ziad Mohamed",
                            Phono = "01234567890"
                        });
                });

            modelBuilder.Entity("CourseStudent", b =>
                {
                    b.HasOne("DAL.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("CoursesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
